// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-l7u7WXoliHin8217YioJEXEvrQogaBM',
    appId: '1:924683058368:web:bb34fdffc347aae9b58125',
    messagingSenderId: '924683058368',
    projectId: 'hx-rydr-app',
    authDomain: 'hx-rydr-app.firebaseapp.com',
    storageBucket: 'hx-rydr-app.appspot.com',
    measurementId: 'G-9HV3GCWRTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_IOYATJYOKfPUsawedfvUWuiHENCt16k',
    appId: '1:924683058368:android:7f394473e2ab640fb58125',
    messagingSenderId: '924683058368',
    projectId: 'hx-rydr-app',
    storageBucket: 'hx-rydr-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU7qMIBr5NZ6MGEp06lLvsMk9zhsQsBp4',
    appId: '1:924683058368:ios:029739e5ffb115c9b58125',
    messagingSenderId: '924683058368',
    projectId: 'hx-rydr-app',
    storageBucket: 'hx-rydr-app.appspot.com',
    iosBundleId: 'com.shs-studiolab.rydr-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU7qMIBr5NZ6MGEp06lLvsMk9zhsQsBp4',
    appId: '1:924683058368:ios:2e0d3f57a50d3ea1b58125',
    messagingSenderId: '924683058368',
    projectId: 'hx-rydr-app',
    storageBucket: 'hx-rydr-app.appspot.com',
    iosBundleId: 'com.example.rydrApp.RunnerTests',
  );
}
